# Generated by Django 5.2.14 on 2026-08-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('running', 'RUNNING'), ('retrying', 'RETRYING'), ('finished', 'FINISHED'), ('failure', 'FAILURE'), ('cancelled', 'CANCELLED')], default='running', max_length=9)),
                ('logs', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('requester_email', models.EmailField(max_length=254)),
                ('report_name', models.CharField(max_length=200)),
                ('information', models.TextField()),
                ('statement_type', models.CharField(choices=[('IS', 'Income Statement'), ('BS', 'Balance Sheet'), ('CF', 'Cash Flow Statement')], default='IS', max_length=2)),
                ('period_type', models.CharField(choices=[('FY', 'Annual (Full Year)'), ('Q', 'Quarterly')], default='FY', max_length=2)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('display_unit', models.CharField(choices=[('1', 'Exact Dollars ($)'), ('1000', 'Thousands ($K)'), ('1000000', 'Millions ($M)')], default='1000000', max_length=10)),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('company_name', models.CharField(max_length=200)),
                ('fiscal_year', models.IntegerField(db_index=True)),
                ('fiscal_period', models.CharField(choices=[('FY', 'Annual (Full Year)'), ('Q', 'Quarterly')], max_length=5)),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
    ]
