# Generated by Django 5.2.14 on 2026-08-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(unique=True)),
                ('status', models.CharField(choices=[('running', 'RUNNING'), ('retrying', 'RETRYING'), ('finished', 'FINISHED'), ('failure', 'FAILURE'), ('cancelled', 'CANCELLED')], default='running', max_length=9)),
                ('logs', models.TextField(blank=True, null=True)),
                ('request_name', models.CharField()),
                ('information', models.TextField()),
                ('requester_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
    ]
