# Generated by Django 5.1.2 on 2026-08-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='sheet_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
