from django.db import models

class Requests(models.Model):
    STATUS = (
        ("running", "RUNNING"),
        ("retrying", "RETRYING"),
        ("finished", "FINISHED"),
        ("failure", "FAILURE"),
        ("cancelled", "CANCELLED"),
    )

    STATEMENT_TYPE = (
        ("IS", "Income Statement"),
        ("BS", "Balance Sheet"),
        ("CF", "Cash Flow Statement"),
    )

    PERIOD_TYPE = (
        ("FY", "Annual (Full Year)"),
        ("Q", "Quarterly"),
    )

    DISPLAY_UNIT = (
        ("1", "Exact Dollars ($)"),
        ("1000", "Thousands ($K)"),
        ("1000000", "Millions ($M)"),
    )

    TICKER_CHOICES = (
        ("AAPL", "AAPL - Apple"),
        ("ABBV", "ABBV - AbbVie"),
        ("ABT", "ABT - Abbott Laboratories"),
        ("ACN", "ACN - Accenture"),
        ("ADBE", "ADBE - Adobe"),
        ("ADI", "ADI - Analog Devices"),
        ("ADM", "ADM - Archer-Daniels-Midland"),
        ("ADP", "ADP - Automatic Data Processing"),
        ("ADSK", "ADSK - Autodesk"),
        ("AEE", "AEE - Ameren"),
        ("AEP", "AEP - American Electric Power"),
        ("AES", "AES - AES Corporation"),
        ("AFL", "AFL - Aflac"),
        ("AIG", "AIG - American International Group"),
        ("AIZ", "AIZ - Assurant"),
        ("AJG", "AJG - Arthur J. Gallagher"),
        ("AKAM", "AKAM - Akamai Technologies"),
        ("ALB", "ALB - Albemarle Corporation"),
        ("ALGN", "ALGN - Align Technology"),
        ("ALL", "ALL - Allstate"),
        ("ALLE", "ALLE - Allegion"),
        ("AMAT", "AMAT - Applied Materials"),
        ("AMCR", "AMCR - Amcor"),
        ("AMD", "AMD - AMD"),
        ("AME", "AME - AMETEK"),
        ("AMGN", "AMGN - Amgen"),
        ("AMP", "AMP - Ameriprise Financial"),
        ("AMT", "AMT - American Tower"),
        ("AMZN", "AMZN - Amazon"),
        ("ANET", "ANET - Arista Networks"),
        ("ANSS", "ANSS - ANSYS"),
        ("AON", "AON - Aon"),
        ("AOS", "AOS - A. O. Smith"),
        ("APA", "APA - APA Corporation"),
        ("APD", "APD - Air Products and Chemicals"),
        ("APH", "APH - Amphenol"),
        ("APTV", "APTV - Aptiv"),
        ("ARE", "ARE - Alexandria Real Estate Equities"),
        ("ATO", "ATO - Atmos Energy"),
        ("AVB", "AVB - AvalonBay Communities"),
        ("AVGO", "AVGO - Broadcom"),
        ("AVY", "AVY - Avery Dennison"),
        ("AWK", "AWK - American Water Works"),
        ("AXON", "AXON - Axon Enterprise"),
        ("AXP", "AXP - American Express"),
        ("AZO", "AZO - AutoZone"),
        ("BA", "BA - Boeing"),
        ("BAC", "BAC - Bank of America"),
        ("BALL", "BALL - Ball Corporation"),
        ("BAX", "BAX - Baxter International"),
        ("BBWI", "BBWI - Bath & Body Works"),
        ("BBY", "BBY - Best Buy"),
        ("BDX", "BDX - Becton Dickinson"),
        ("BEN", "BEN - Franklin Resources"),
        ("BF.B", "BF.B - Brown-Forman"),
        ("BG", "BG - Bunge Global"),
        ("BIIB", "BIIB - Biogen"),
        ("BIO", "BIO - Bio-Rad Laboratories"),
        ("BK", "BK - BNY Mellon"),
        ("BKNG", "BKNG - Booking Holdings"),
        ("BKR", "BKR - Baker Hughes"),
        ("BLDR", "BLDR - Builders FirstSource"),
        ("BLK", "BLK - BlackRock"),
        ("BMY", "BMY - Bristol Myers Squibb"),
        ("BR", "BR - Broadridge Financial Solutions"),
        ("BRK.B", "BRK.B - Berkshire Hathaway"),
        ("BRO", "BRO - Brown & Brown"),
        ("BSX", "BSX - Boston Scientific"),
        ("BWA", "BWA - BorgWarner"),
        ("BX", "BX - Blackstone"),
        ("BXP", "BXP - BXP Inc."),
        ("C", "C - Citigroup"),
        ("CAG", "CAG - Conagra Brands"),
        ("CAH", "CAH - Cardinal Health"),
        ("CARR", "CARR - Carrier Global"),
        ("CAT", "CAT - Caterpillar"),
        ("CB", "CB - Chubb"),
        ("CBRE", "CBRE - CBRE Group"),
        ("CCI", "CCI - Crown Castle"),
        ("CCJ", "CCJ - Cameco"),
        ("CCL", "CCL - Carnival Corporation"),
        ("CDNS", "CDNS - Cadence Design Systems"),
        ("CDW", "CDW - CDW Corporation"),
        ("CE", "CE - Celanese"),
        ("CEG", "CEG - Constellation Energy"),
        ("CF", "CF - CF Industries"),
        ("CFG", "CFG - Citizens Financial Group"),
        ("CHD", "CHD - Church & Dwight"),
        ("CHRW", "CHRW - C.H. Robinson"),
        ("CHTR", "CHTR - Charter Communications"),
        ("CI", "CI - Cigna"),
        ("CINF", "CINF - Cincinnati Financial"),
        ("CL", "CL - Colgate-Palmolive"),
        ("CLX", "CLX - Clorox"),
        ("CMA", "CMA - Comerica"),
        ("CMCSA", "CMCSA - Comcast"),
        ("CME", "CME - CME Group"),
        ("CMG", "CMG - Chipotle Mexican Grill"),
        ("CMI", "CMI - Cummins"),
        ("CMS", "CMS - CMS Energy"),
        ("CNC", "CNC - Centene"),
        ("CNP", "CNP - CenterPoint Energy"),
        ("COF", "COF - Capital One"),
        ("COO", "COO - CooperCompanies"),
        ("COP", "COP - ConocoPhillips"),
        ("COR", "COR - Cencora"),
        ("COST", "COST - Costco"),
        ("CPB", "CPB - Campbell Soup"),
        ("CPT", "CPT - Camden Property Trust"),
        ("CRL", "CRL - Charles River Laboratories"),
        ("CRM", "CRM - Salesforce"),
        ("CSGP", "CSGP - CoStar Group"),
        ("CSX", "CSX - CSX Corporation"),
        ("CTAS", "CTAS - Cintas"),
        ("CTRA", "CTRA - Coterra Energy"),
        ("CTSH", "CTSH - Cognizant"),
        ("CTVA", "CTVA - Corteva"),
        ("CVS", "CVS - CVS Health"),
        ("CVX", "CVX - Chevron"),
        ("CZR", "CZR - Caesars Entertainment"),
        ("D", "D - Dominion Energy"),
        ("DAL", "DAL - Delta Air Lines"),
        ("DAY", "DAY - Dayforce"),
        ("DD", "DD - DuPont"),
        ("DE", "DE - John Deere"),
        ("DECK", "DECK - Deckers Outdoor"),
        ("DFS", "DFS - Discover Financial"),
        ("DG", "DG - Dollar General"),
        ("DGX", "DGX - Quest Diagnostics"),
        ("DHI", "DHI - D.R. Horton"),
        ("DHR", "DHR - Danaher"),
        ("DIS", "DIS - Walt Disney"),
        ("DLR", "DLR - Digital Realty"),
        ("DLTR", "DLTR - Dollar Tree"),
        ("DOC", "DOC - Healthpeak Properties"),
        ("DOV", "DOV - Dover Corporation"),
        ("DOW", "DOW - Dow Inc."),
        ("DPZ", "DPZ - Domino's Pizza"),
        ("DRI", "DRI - Darden Restaurants"),
        ("DTE", "DTE - DTE Energy"),
        ("DUK", "DUK - Duke Energy"),
        ("DVA", "DVA - DaVita"),
        ("DVN", "DVN - Devon Energy"),
        ("DXCM", "DXCM - DexCom"),
        ("EA", "EA - Electronic Arts"),
        ("EBAY", "EBAY - eBay"),
        ("ECL", "ECL - Ecolab"),
        ("ED", "ED - Consolidated Edison"),
        ("EFX", "EFX - Equifax"),
        ("EG", "EG - Everest Group"),
        ("EIX", "EIX - Edison International"),
        ("EL", "EL - Estée Lauder"),
        ("ELV", "ELV - Elevance Health"),
        ("EMN", "EMN - Eastman Chemical"),
        ("EMR", "EMR - Emerson Electric"),
        ("ENPH", "ENPH - Enphase Energy"),
        ("EOG", "EOG - EOG Resources"),
        ("EPAM", "EPAM - EPAM Systems"),
        ("EQIX", "EQIX - Equinix"),
        ("EQR", "EQR - Equity Residential"),
        ("EQT", "EQT - EQT Corporation"),
        ("ERIE", "ERIE - Erie Indemnity"),
        ("ES", "ES - Eversource Energy"),
        ("ESS", "ESS - Essex Property Trust"),
        ("ETN", "ETN - Eaton Corporation"),
        ("ETR", "ETR - Entergy"),
        ("EVRG", "EVRG - Evergy"),
        ("EW", "EW - Edwards Lifesciences"),
        ("EXC", "EXC - Exelon"),
        ("EXPD", "EXPD - Expeditors International"),
        ("EXPE", "EXPE - Expedia Group"),
        ("EXR", "EXR - Extra Space Storage"),
        ("F", "F - Ford Motor Company"),
        ("FANG", "FANG - Diamondback Energy"),
        ("FAST", "FAST - Fastenal"),
        ("FCX", "FCX - Freeport-McMoRan"),
        ("FDS", "FDS - FactSet"),
        ("FDX", "FDX - FedEx"),
        ("FE", "FE - FirstEnergy"),
        ("FFIV", "FFIV - F5 Inc."),
        ("FI", "FI - Fiserv"),
        ("FICO", "FICO - Fair Isaac Corporation"),
        ("FIS", "FIS - FIS"),
        ("FITB", "FITB - Fifth Third Bank"),
        ("FLT", "FLT - Fleetcor Technologies"),
        ("FMC", "FMC - FMC Corporation"),
        ("FOX", "FOX - Fox Corporation (Class B)"),
        ("FOXA", "FOXA - Fox Corporation (Class A)"),
        ("FRT", "FRT - Federal Realty Investment Trust"),
        ("FSLR", "FSLR - First Solar"),
        ("FTNT", "FTNT - Fortinet"),
        ("FTV", "FTV - Fortive"),
        ("GD", "GD - General Dynamics"),
        ("GDDY", "GDDY - GoDaddy"),
        ("GE", "GE - General Electric"),
        ("GEHC", "GEHC - GE HealthCare"),
        ("GEN", "GEN - Gen Digital"),
        ("GEV", "GEV - GE Vernova"),
        ("GILD", "GILD - Gilead Sciences"),
        ("GIS", "GIS - General Mills"),
        ("GL", "GL - Globe Life"),
        ("GLW", "GLW - Corning"),
        ("GM", "GM - General Motors"),
        ("GNRC", "GNRC - Generac"),
        ("GOOG", "GOOG - Alphabet (Class C)"),
        ("GOOGL", "GOOGL - Alphabet (Class A)"),
        ("GPC", "GPC - Genuine Parts Company"),
        ("GPN", "GPN - Global Payments"),
        ("GRMN", "GRMN - Garmin"),
        ("GS", "GS - Goldman Sachs"),
        ("GWW", "GWW - W.W. Grainger"),
        ("HAL", "HAL - Halliburton"),
        ("HAS", "HAS - Hasbro"),
        ("HBAN", "HBAN - Huntington Bancshares"),
        ("HCA", "HCA - HCA Healthcare"),
        ("HD", "HD - Home Depot"),
        ("HES", "HES - Hess Corporation"),
        ("HIG", "HIG - The Hartford"),
        ("HII", "HII - Huntington Ingalls Industries"),
        ("HLT", "HLT - Hilton Worldwide"),
        ("HOLX", "HOLX - Hologic"),
        ("HON", "HON - Honeywell"),
        ("HPE", "HPE - Hewlett Packard Enterprise"),
        ("HPQ", "HPQ - HP Inc."),
        ("HRL", "HRL - Hormel Foods"),
        ("HSIC", "HSIC - Henry Schein"),
        ("HST", "HST - Host Hotels & Resorts"),
        ("HSY", "HSY - The Hershey Company"),
        ("HUBB", "HUBB - Hubbell Incorporated"),
        ("HUM", "HUM - Humana"),
        ("HWM", "HWM - Howmet Aerospace"),
        ("IBM", "IBM - IBM"),
        ("ICE", "ICE - Intercontinental Exchange"),
        ("IDXX", "IDXX - IDEXX Laboratories"),
        ("IEX", "IEX - IDEX Corporation"),
        ("IFF", "IFF - International Flavors & Fragrances"),
        ("INCY", "INCY - Incyte"),
        ("INTC", "INTC - Intel"),
        ("INTU", "INTU - Intuit"),
        ("INVH", "INVH - Invitation Homes"),
        ("IP", "IP - International Paper"),
        ("IPG", "IPG - Interpublic Group"),
        ("IQV", "IQV - IQVIA"),
        ("IR", "IR - Ingersoll Rand"),
        ("IRM", "IRM - Iron Mountain"),
        ("ISRG", "ISRG - Intuitive Surgical"),
        ("IT", "IT - Gartner"),
        ("ITW", "ITW - Illinois Tool Works"),
        ("IVZ", "IVZ - Invesco"),
        ("J", "J - Jacobs Solutions"),
        ("JBHT", "JBHT - J.B. Hunt"),
        ("JCI", "JCI - Johnson Controls"),
        ("JKHY", "JKHY - Jack Henry & Associates"),
        ("JNJ", "JNJ - Johnson & Johnson"),
        ("JNPR", "JNPR - Juniper Networks"),
        ("JPM", "JPM - JPMorgan Chase"),
        ("K", "K - Kellanova"),
        ("KAC", "KAC - KB Home"),
        ("KDP", "KDP - Keurig Dr Pepper"),
        ("KEY", "KEY - KeyCorp"),
        ("KEYS", "KEYS - Keysight Technologies"),
        ("KIM", "KIM - Kimco Realty"),
        ("BMI", "BMI - Badger Meter"),
        ("KLAC", "KLAC - KLA Corporation"),
        ("KMB", "KMB - Kimberly-Clark"),
        ("KMX", "KMX - CarMax"),
        ("KO", "KO - Coca-Cola"),
        ("KR", "KR - Kroger"),
        ("KVUE", "KVUE - Kenvue"),
        ("L", "L - Loews Corporation"),
        ("LDOS", "LDOS - Leidos"),
        ("LEN", "LEN - Lennar"),
        ("LH", "LH - Labcorp"),
        ("LHX", "LHX - L3Harris Technologies"),
        ("LIN", "LIN - Linde plc"),
        ("LKQ", "LKQ - LKQ Corporation"),
        ("LLY", "LLY - Eli Lilly"),
        ("LMT", "LMT - Lockheed Martin"),
        ("LNT", "LNT - Alliant Energy"),
        ("LOW", "LOW - Lowe's"),
        ("LRCX", "LRCX - Lam Research"),
        ("LULI", "LULI - Lululemon Athletica"),
        ("LUV", "LUV - Southwest Airlines"),
        ("LVS", "LVS - Las Vegas Sands"),
        ("LW", "LW - Lamb Weston"),
        ("LYB", "LYB - LyondellBasell"),
        ("LYV", "LYV - Live Nation Entertainment"),
        ("MA", "MA - Mastercard"),
        ("MAA", "MAA - Mid-America Apartment Communities"),
        ("MAR", "MAR - Marriott International"),
        ("MAS", "MAS - Masco Corporation"),
        ("MCD", "MCD - McDonald's"),
        ("MCHP", "MCHP - Microchip Technology"),
        ("MCK", "MCK - McKesson"),
        ("MCO", "MCO - Moody's Corporation"),
        ("MDLZ", "MDLZ - Mondelez International"),
        ("MDT", "MDT - Medtronic"),
        ("MET", "MET - MetLife"),
        ("META", "META - Meta Platforms"),
        ("MGM", "MGM - MGM Resorts International"),
        ("MHK", "MHK - Mohawk Industries"),
        ("MKC", "MKC - McCormick & Company"),
        ("MKTX", "MKTX - MarketAxess"),
        ("MLM", "MLM - Martin Marietta Materials"),
        ("MMC", "MMC - Marsh McLennan"),
        ("MMM", "MMM - 3M"),
        ("MNST", "MNST - Monster Beverage"),
        ("MO", "MO - Altria Group"),
        ("MOH", "MOH - Molina Healthcare"),
        ("MOS", "MOS - The Mosaic Company"),
        ("MPC", "MPC - Marathon Petroleum"),
        ("MPWR", "MPWR - Monolithic Power Systems"),
        ("MRK", "MRK - Merck"),
        ("MRNA", "MRNA - Moderna"),
        ("MRO", "MRO - Marathon Oil"),
        ("MS", "MS - Morgan Stanley"),
        ("MSCI", "MSCI - MSCI Inc."),
        ("MSFT", "MSFT - Microsoft"),
        ("MSI", "MSI - Motorola Solutions"),
        ("MTB", "MTB - M&T Bank"),
        ("MTD", "MTD - Mettler-Toledo"),
        ("MU", "MU - Micron Technology"),
        ("NCLH", "NCLH - Norwegian Cruise Line Holdings"),
        ("NDAQ", "NDAQ - Nasdaq, Inc."),
        ("NDSN", "NDSN - Nordson Corporation"),
        ("NEE", "NEE - NextEra Energy"),
        ("NEM", "NEM - Newmont"),
        ("NFLX", "NFLX - Netflix"),
        ("NI", "NI - NiSource"),
        ("NKE", "NKE - Nike"),
        ("NOC", "NOC - Northrop Grumman"),
        ("NOW", "NOW - ServiceNow"),
        ("NRG", "NRG - NRG Energy"),
        ("NSC", "NSC - Norfolk Southern"),
        ("NTAP", "NTAP - NetApp"),
        ("NTRS", "NTRS - Northern Trust"),
        ("NUE", "NUE - Nucor"),
        ("NVDA", "NVDA - NVIDIA"),
        ("NVR", "NVR - NVR, Inc."),
        ("NWS", "NWS - News Corp (Class B)"),
        ("NWSA", "NWSA - News Corp (Class A)"),
        ("NXPI", "NXPI - NXP Semiconductors"),
        ("O", "O - Realty Income"),
        ("ODFL", "ODFL - Old Dominion Freight Line"),
        ("OKE", "OKE - ONEOK"),
        ("OMC", "OMC - Omnicom Group"),
        ("ON", "ON - ON Semiconductor"),
        ("ORLY", "ORLY - O'Reilly Auto Parts"),
        ("ORCL", "ORCL - Oracle"),
        ("OTIS", "OTIS - Otis Worldwide"),
        ("PCAR", "PCAR - PACCAR"),
        ("PCG", "PCG - PG&E Corporation"),
        ("PEG", "PEG - Public Service Enterprise Group"),
        ("PEP", "PEP - PepsiCo"),
        ("PFE", "PFE - Pfizer"),
        ("PFG", "PFG - Principal Financial Group"),
        ("PG", "PG - Procter & Gamble"),
        ("PGR", "PGR - Progressive"),
        ("PH", "PH - Parker-Hannifin"),
        ("PHM", "PHM - PulteGroup"),
        ("PKG", "PKG - Packaging Corporation of America"),
        ("PLD", "PLD - Prologis"),
        ("PM", "PM - Philip Morris International"),
        ("PNC", "PNC - PNC Financial Services"),
        ("PNR", "PNR - Pentair"),
        ("PNW", "PNW - Pinnacle West Capital"),
        ("PODD", "PODD - Insulet Corporation"),
        ("POOL", "POOL - Pool Corporation"),
        ("PPG", "PPG - PPG Industries"),
        ("PPL", "PPL - PPL Corporation"),
        ("PRU", "PRU - Prudential Financial"),
        ("PSA", "PSA - Public Storage"),
        ("PSX", "PSX - Phillips 66"),
        ("PTC", "PTC - PTC Inc."),
        ("PWR", "PWR - Quanta Services"),
        ("PYPL", "PYPL - PayPal"),
        ("QCOM", "QCOM - Qualcomm"),
        ("QRVO", "QRVO - Qorvo"),
        ("RCL", "RCL - Royal Caribbean Group"),
        ("REG", "REG - Regency Centers"),
        ("REGN", "REGN - Regeneron Pharmaceuticals"),
        ("RF", "RF - Regions Financial"),
        ("RJF", "RJF - Raymond James Financial"),
        ("RL", "RL - Ralph Lauren"),
        ("RMD", "RMD - ResMed"),
        ("ROK", "ROK - Rockwell Automation"),
        ("ROL", "ROL - Rollins, Inc."),
        ("ROP", "ROP - Roper Technologies"),
        ("ROST", "ROST - Ross Stores"),
        ("RSG", "RSG - Republic Services"),
        ("RTX", "RTX - RTX Corporation"),
        ("RVTY", "RVTY - Revvity"),
        ("SBAC", "SBAC - SBA Communications"),
        ("SBUX", "SBUX - Starbucks"),
        ("SCHW", "SCHW - Charles Schwab"),
        ("SHW", "SHW - Sherwin-Williams"),
        ("SJM", "SJM - J.M. Smucker"),
        ("SLB", "SLB - Schlumberger"),
        ("SNA", "SNA - Snap-on"),
        ("SNPS", "SNPS - Synopsys"),
        ("SO", "SO - Southern Company"),
        ("SPG", "SPG - Simon Property Group"),
        ("SPGI", "SPGI - S&P Global"),
        ("SRE", "SRE - Sempra"),
        ("STE", "STE - STERIS"),
        ("STLD", "STLD - Steel Dynamics"),
        ("STT", "STT - State Street"),
        ("STX", "STX - Seagate Technology"),
        ("STZ", "STZ - Constellation Brands"),
        ("SWK", "SWK - Stanley Black & Decker"),
        ("SWKS", "SWKS - Skyworks Solutions"),
        ("SYF", "SYF - Synchrony Financial"),
        ("SYK", "SYK - Stryker"),
        ("SYY", "SYY - Sysco"),
        ("T", "T - AT&T"),
        ("TAP", "TAP - Molson Coors Beverage Company"),
        ("TDG", "TDG - TransDigm Group"),
        ("TDY", "TDY - Teledyne Technologies"),
        ("TECH", "TECH - Bio-Techne"),
        ("TEL", "TEL - TE Connectivity"),
        ("TER", "TER - Teradyne"),
        ("TFC", "TFC - Truist Financial"),
        ("TFX", "TFX - Teleflex"),
        ("TGT", "TGT - Target"),
        ("TJX", "TJX - TJX Companies"),
        ("TMO", "TMO - Thermo Fisher Scientific"),
        ("TMUS", "TMUS - T-Mobile US"),
        ("TPR", "TPR - Tapestry"),
        ("TRGP", "TRGP - Targa Resources"),
        ("TRMB", "TRMB - Trimble Inc."),
        ("TROW", "TROW - T. Rowe Price"),
        ("TRV", "TRV - The Travelers Companies"),
        ("TSCO", "TSCO - Tractor Supply Company"),
        ("TSLA", "TSLA - Tesla"),
        ("TSN", "TSN - Tyson Foods"),
        ("TT", "TT - Trane Technologies"),
        ("TTWO", "TTWO - Take-Two Interactive"),
        ("TXN", "TXN - Texas Instruments"),
        ("TXT", "TXT - Textron"),
        ("TYL", "TYL - Tyler Technologies"),
        ("UAL", "UAL - United Airlines Holdings"),
        ("UDR", "UDR - UDR, Inc."),
        ("UHS", "UHS - Universal Health Services"),
        ("ULTA", "ULTA - Ulta Beauty"),
        ("UNH", "UNH - UnitedHealth Group"),
        ("UNP", "UNP - Union Pacific"),
        ("UPS", "UPS - United Parcel Service"),
        ("URI", "URI - United Rentals"),
        ("USB", "USB - U.S. Bancorp"),
        ("V", "V - Visa"),
        ("VICI", "VICI - VICI Properties"),
        ("VLO", "VLO - Valero Energy"),
        ("VLTO", "VLTO - Veralto"),
        ("VMC", "VMC - Vulcan Materials"),
        ("VRSK", "VRSK - Verisk Analytics"),
        ("VRSN", "VRSN - VeriSign"),
        ("VRTX", "VRTX - Vertex Pharmaceuticals"),
        ("VST", "VST - Vistra Corp."),
        ("VTR", "VTR - Ventas"),
        ("VTRS", "VTRS - Viatris"),
        ("VZ", "VZ - Verizon Communications"),
        ("WAB", "WAB - Westinghouse Air Brake Technologies"),
        ("WAT", "WAT - Waters Corporation"),
        ("WBA", "WBA - Walgreens Boots Alliance"),
        ("WBD", "WBD - Warner Bros. Discovery"),
        ("MDB", "MDB - MongoDB"),
        ("WDC", "WDC - Western Digital"),
        ("WEC", "WEC - WEC Energy Group"),
        ("WELL", "WELL - Welltower"),
        ("WFC", "WFC - Wells Fargo"),
        ("WM", "WM - Waste Management"),
        ("WMB", "WMB - Williams Companies"),
        ("WMT", "WMT - Walmart"),
        ("WRB", "WRB - W. R. Berkley"),
        ("WRK", "WRK - WestRock"),
        ("WST", "WST - West Pharmaceutical Services"),
        ("WTW", "WTW - Willis Towers Watson"),
        ("WY", "WY - Weyerhaeuser"),
        ("WYNN", "WYNN - Wynn Resorts"),
        ("XEL", "XEL - Xcel Energy"),
        ("XOM", "XOM - ExxonMobil"),
        ("XYL", "XYL - Xylem"),
        ("YUM", "YUM - Yum! Brands"),
        ("ZBRA", "ZBRA - Zebra Technologies"),
        ("ZBH", "ZBH - Zimmer Biomet"),
        ("ZTS", "ZTS - Zoetis"),
    )

    # Task & Metadata
    task_id = models.CharField(max_length=255, unique=True)
    status = models.CharField(max_length=9, choices=STATUS, default="running")
    logs = models.TextField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    requester_email = models.EmailField()

    # User Request Inputs
    report_name = models.CharField(max_length=200)
    information = models.TextField()
    tickers = models.JSONField(default=list)
    statement_type = models.CharField(max_length=2, choices=STATEMENT_TYPE, default="IS")
    period_type = models.CharField(max_length=2, choices=PERIOD_TYPE, default="FY")
    start_year = models.IntegerField()
    end_year = models.IntegerField()
    display_unit = models.CharField(max_length=10, choices=DISPLAY_UNIT, default="1000000")
    
    # Output
    sheet_url = models.URLField(null=True, blank=True)

    class Meta:
        verbose_name = "Request"
        verbose_name_plural = "Requests"

    def __str__(self):
        return self.report_name